import React, { useState } from "react";
import axios from "axios";

function Filter({ onFilterChange }) {
  const [selectedFilters, setSelectedFilters] = useState({
    topic: "",
    endYear: "",
    sector: "",
    region: "",
    PEST: "",
    source: "",
    SWOT: "",
    country: "",
    city: "",
  });

  const uniqueTopic = [
    "election",
    "pollution",
    "debt",
    "crisis",
    "carbon",
    "greenhouse gas",
    "shortage",
    "worker",
    "business",
    "economic growth",
    "peak oil",
    "industry",
    "terrorism",
    "population",
    "food",
    "information",
    "storm",
    "gdp",
    "tourist",
    "communication",
    "vehicle",
    "interest rate",
    "tension",
    "transport",
    "workforce",
    "coal",
    "battery",
    "software",
    "oil",
    "artificial intelligence",
    "demand",
    "factory",
    "security",
    "3D",
    "data",
    "gasoline",
    "wealth",
    "fossil fuel",
    "gamification",
    "government",
    "farm",
    "money",
    "nuclear",
    "risk",
    "inflation",
    "gas",
    "policy",
    "work",
    "biofuel",
    "transportation",
    "material",
    "war",
    "consumer",
    "ice",
    "electricity",
    "building",
    "plastic",
    "revenue",
    "climate change",
    "unemployment",
    "strategy",
    "change",
    "export",
    "robot",
    "energy",
    "asylum",
    "consumption",
    "clothing",
    "shale gas",
    "automaker",
    "brexit",
    "politics",
    "market",
    "water",
    "capital",
    "emission",
    "tax",
    "growth",
    "agriculture",
    "fracking",
    "technology",
    "car",
    "infrastructure",
    "economy",
    "resource",
    "climate",
    "production",
    "bank",
    "investment",
    "administration",
    "aquaculture",
    "trade",
    "city",
    "economic",
    "Washington",
    "power",
    "finance",
  ];

  const endYear = [
    2036, 2034, 2051, 2200, 2041, 2060, 2126, 2030, 2017, 2028, 2019, 2025,
    2024, 2022, 2046, 2020, 2016, 2018, 2035, 2050, 2021, 2040, 2026, 2027,
    2055,
  ];

  const uniqueSector = [
    "Environment",
    "Security",
    "Automotive",
    "Government",
    "Water",
    "Financial services",
    "Energy",
    "Food & agriculture",
    "Tourism & hospitality",
    "Support services",
    "Information Technology",
    "Retail",
    "Manufacturing",
    "Aerospace & defence",
    "Media & entertainment",
    "Transport",
    "Construction",
    "Healthcare",
  ];

  const uniqueRegion = [
    "Central Africa",
    "Eastern Asia",
    "Southern Africa",
    "Africa",
    "world",
    "Western Asia",
    "Central Asia",
    "Europe",
    "Asia",
    "World",
    "Northern Africa",
    "Northern Europe",
    "Southern Europe",
    "Eastern Africa",
    "Eastern Europe",
    "Southern Asia",
    "Oceania",
    "Northern America",
    "South America",
    "Western Africa",
    "Central America",
    "Western Europe",
    "South-Eastern Asia",
  ];

  const uniquePEST = [
    "Healthcare",
    "Environmental",
    "Lifestyles",
    "Industries",
    "Political",
    "Technological",
    "Economic",
    "Organization",
    "Social",
  ];

  const uniqueSource = [
    "the star online",
    "Sputnik News",
    "Gizmodo Australia",
    "thespanisheconomy",
    "News.com",
    "Guardian Sustainable Business",
    "Society of Motor Manufacturers and Traders (SMMT)",
    "GlobalMeatNews.com",
    "idc-community",
    "friday-thinking",
    "portfolioticker",
    "Channel News Asia",
    "iMFdirect - The IMF Blog",
    "Cars.co.za",
    "valburyresearch",
    "The Chirographer",
    "The Market Mogul",
    "westpandi",
    "RiskMap 2017",
    "Europa",
    "Yes Bank",
    "IER",
    "Peak Prosperity",
    "Nanotechnology Innovation",
    "unian",
    "greenerearthnews",
    "saltlakecityheadlines",
    "EPA",
    "Embedded Computing Design",
    "Digitalist Magazine",
    "Avi Melamed",
    "Transport Environment",
    "energyglobal",
    "Oil and Gas Journal",
    "Prospects for Development",
    "FutureinFocus",
    "platts",
    "dpaq",
    "globalmoneytrends",
    "Global Money Trends",
    "g7g20",
    "Aljazeera.com",
    "McKinsey Quarterly",
    "TRAC News",
    "Future Earth",
    "Lawfare",
    "Hospitality Trends",
    "arabellaadvisors",
    "Citibank",
    "CAJ News Africa",
    "Climate News Network",
    "Strategy & Formerly Booz & Company",
    "Planetizen",
    "environmentalpeacebuilding",
    "NWF",
    "About Best Binary Options Strategy",
    "The Mainichi",
    "Scientific American",
    "Neon Nettle",
    "Think Progress",
    "Cushman & Wakefield",
    "Azonano",
    "U.S. Environmental Protection Agency",
    "Wood McKenzie",
    "The Independent",
    "Energy Tomorrow",
    "Business Green",
    "International Banker",
    "bankofengland",
    "Face2face Africa",
    "EGYPS",
    "Resilience",
    "Energy.gov Website",
    "www.narendramodi.in",
    "theicct",
    "CDC",
    "Yahoo Finance",
    "PR Newswire",
    "WSJ",
    "Business Wire",
    "Cii Radio",
    "Inside Climate News",
    "Washington Post",
    "ID TECH INDEX",
    "IBEF",
    "MENA-Forum",
    "EY",
    "Drill or drop?",
    "The Conversation",
    "Science Daily",
    "biomassmagazine",
    "What's Next",
    "Pickens Plan",
    "FAO",
    "New Security Beat",
    "Middle East Online",
    "CleanTechnica",
    "Critical Threats",
    "Newsweek",
    "Drydock Magazine",
    "Farms.com",
    "Arangkada Philippines",
    "EIA",
    "International Business Times",
    "Russia Beyond The Headlines",
    "ethicalmarkets",
    "Total",
    "Resources for the Future",
    "Le·gal In·sur·rec·tion",
    "Slinking Toward Retirement",
    "The Globe and Mail",
    "Engineering News",
    "OMFIF",
    "dailyquiddity",
    "IMF",
    "Gii Research",
    "nbk",
    "Carbon Brief",
    "Convenience Store Decisions",
    "Insurance Journal",
    "FX Empire",
    "THISDAY LIVE",
    "Future in Focus",
    "Euromoney",
    "UNESCO ",
    "Nature",
    "globalr2p",
    "Predictive Analytics Times",
    "THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA",
    "Scania Group",
    "Rigzone",
    "African Development Bank",
    "South World",
    "uschamber",
    "IHS Engineering 360",
    "SBWire",
    "International Monetary Fund (IMF)",
    "Interior Design",
    "Imeche",
    "Maplecroft",
    "Wired UK",
    "CIO",
    "Wikipedia",
    "GreenBiz",
    "3D Printing Progress",
    "IASTOPPERS",
    "Industry Week",
    "VOA",
    "The Jakarta Post",
    "cloudfront",
    "DW.COM",
    "BBC News Technology",
    "Motor Magazine",
    "Time",
    "Brookings Institute",
    "PwC",
    "Future Timeline",
    "ihsmarkit",
    "Guarini Center",
    "TheNews.NG",
    "Tech Times",
    "Wharton",
    "ethicalconsumer",
    "Robothub",
    "Days Of Year",
    "Wells Fargo",
    "bankofcanada",
    "CSIS",
    "Climate Change News",
    "UNEP",
    "cpzulia",
    "Technavio",
    "amundi",
    "INSEAD Knowledge",
    "Cornell University",
    "Media Center ",
    "Infracircle",
    "University Chronicle",
    "Wall Street Daily",
    "The Next Web",
    "European Central Bank",
    "The Nation",
    "Quartz",
    "energy news cyprus",
    "NY Times",
    "economy",
    "VITA Technologies",
    "European Environment Agency",
    "Adam Curry",
    "EIU",
    "FashionNetwork.com",
    "EE News",
    "djsresearch",
    "Mind Commerce",
    "sustainablebrands.com",
    "IRENA",
    "ecesr",
    "Virgin Atlantic",
    "Countries.com Global Content",
    "Elsevier",
    "inputsmonitor",
    "Oxfam",
    "Innovations Report",
    "The Guardian",
    "TeleTrade",
    "allianzglobalinvestors",
    "Freedonia",
    "EV Obsession",
    "Australian Government Department of Defence",
    "Fitch",
    "dailytexanonline",
    "Abq",
    "Institutional Investor",
    "AgWeb - The Home Page of Agriculture",
    "CBO",
    "Politico",
    "JD Supra",
    "The Ticker Tape",
    "Environmental Leader",
    "LNG",
    "edie.net",
    "metalprices",
    "War on the Rocks",
    "Seeking Alpha",
    "Global Information Inc",
    "World Bank",
    "Star Tribune",
    "University of Chicago",
    "AMERICAN COUNCIL ON SCIENCE AND HEALTH",
    "clientadvisoryservices",
    "South China Morning Post",
    "MRC",
    "Project Syndicate",
    "farms",
    "watercanada",
    "Hardin Tibbs",
    "Edge and Odds",
    "MIT Technology Review",
    "jeita",
    "prsync",
    "Fast Co-Exist",
    "IISS",
    "Canadian Biomass",
    "Shenandoah",
    "Huffington Post",
    "South Sudan News Agency",
    "IFT",
    "OklahomaMinerals.com",
    "Mast",
    "savepassamaquoddybay",
    "Gartner",
    "TheCable",
    "IEA.org",
    "IEA",
    "Ocean Acidification",
    "Government of Ireland",
    "Real Estate Professional",
    "Smart Grid Observer",
    "Industrial Control Security",
    "Activist Post",
    "controleng",
    "GE Reports",
    "agriworldsa",
    "Utility Dive",
    "MAPI",
    "McKinsey & Company",
    "U.K. Ministry of Defense",
    "ESPAS",
    "Euler Hermes",
    "Verisk Maplecroft",
    "Investopedia",
    "Biofuels Digest",
    "worldenergy",
    "njc-cnm",
    "Nation of Change",
    "Informed Choice Chartered Financial Planners in Cranleigh",
    "Zero Hedge",
    "europeanclimate",
    "Zawya",
    "IRENA newsroom",
    "ogauthority",
    "PDQFX news",
    "knomad",
    "OPEC",
    "Physics World",
    "CNBC ",
    "veteranstoday",
    "African Arguments",
    "Blue and Green Tomorrow",
    "LiveMint",
    "FoodQualityNews.com",
    "Nexus Conference",
    "Khaleej Times",
    "Fews Net",
    "SlideShare",
    "CNNMoney",
    "Triple Pundit",
    "Before It's News | Alternative News | UFO | Beyond Science | True News| Prophecy News | People Powered News",
    "University of Latvia",
    "polymerspaintcolourjournal",
    "News",
    "Tactical Investor",
    "ebrd",
    "Reuters",
    "globalfueleconomy",
    "biologicaldiversity",
    "Sydney Morning Herald",
    "Innovate UK",
    "The Jamestown Foundation",
    "Atlantic Council ",
    "The American Prospect",
    "Freenewspos",
    "CAFrackFacts",
    "khorreports-palmoil",
    "Common Dreams",
    "CCN: Financial Bitcoin & Cryptocurrency News",
    "AHDB",
    "betterenergy",
    "World Bank Group",
    "PriceWaterhouseCoopers",
    "nbp",
    "Handelsblatt Global Edition",
    "European Council",
    "The Atlantic",
    "EPS News",
    "worldculturepictorial",
    "ETEnergyworld.com",
    "Vanguard News",
    "Futurity",
    "cargill",
    "The Engineer",
    "Planetsave ",
    "Eurasia Group",
    "murc",
    "ECFR",
    "Foreign Policy",
    "Innovaro",
    "AllAfrica",
    "The Economist",
    "Global Money Trends Magazine",
    "Middle East Eye",
    "Thomson Reuters ",
    "DOE EIA 2013 Energy Conference",
    "maltawinds.com",
    "Business Insider",
    "NDTV",
    "MIT Sloan Management Review",
    "National Geographic Society (blogs)",
    "Future Market Insights",
    "Cushman & Wakefield Blog",
    "iamericas",
    "BorneoPost Online",
    "Koenig Investment Advisory",
    "Business Standard",
    "Bloomberg Business",
    "Worldly",
    "Fox Business",
    "oilprice.com",
    "USDA",
    "HBR",
    "Stanford News",
    "Gas 2",
    "Guardian",
    "No 2 Nuclear Power",
    "Renewable Energy World",
    "aswm",
    "conferenceseries",
    "The Arab Gulf States Institute Washington",
    "atradius",
    "globalizationpartners",
    "Manufacturing Operations Technology Viewpoints",
    "Yahoo Finance Canada",
    "Vox",
    "ReadWrite",
    "RUSI",
    "Phys Org",
    "briandcolwell",
    "satprnews",
    "Bearnobull",
    "Eco-Business.com",
    "newscientist",
    "Jachin Capital",
    "Transport Evolved",
    "Justmeans",
    "marketrealist",
    "therobotreport",
    "Finance Magnates",
    "oilvoice",
    "OEM/Lube News",
    "UK Government",
    "Futureseek Link Digest",
    "Australian Government",
    "Science News",
    "4th Annual Congress and Expo on Biofuels and Bioenergy April 27-28 2017 Dubai UAE",
    "gasstrategies",
    "Europe in My Region",
    "creamermedia",
    "ISA",
    "World Health",
    "Bloomberg New Energy Finance",
    "nextbigfuture",
    "World Energy News",
    "Newsletter",
  ];

  const uniqueCountry = [
    "Austria",
    "Syria",
    "Kazakhstan",
    "Saudi Arabia",
    "Argentina",
    "Colombia",
    "Morocco",
    "Ethiopia",
    "South Sudan",
    "United Kingdom",
    "Iraq",
    "Angola",
    "Cyprus",
    "Pakistan",
    "Australia",
    "Algeria",
    "Mali",
    "Estonia",
    "Brazil",
    "Canada",
    "Hungary",
    "South Africa",
    "India",
    "Kuwait",
    "Germany",
    "Poland",
    "Gabon",
    "Japan",
    "Mexico",
    "Ukraine",
    "Qatar",
    "Norway",
    "United Arab Emirates",
    "Turkey",
    "China",
    "Burkina Faso",
    "Ghana",
    "Niger",
    "Russia",
    "Malaysia",
    "Lebanon",
    "Liberia",
    "Indonesia",
    "Iran",
    "Nigeria",
    "Greece",
    "Spain",
    "Egypt",
    "Denmark",
    "Venezuela",
    "United States of America",
    "Libya",
    "Belize",
    "Azerbaijan",
    "Jordan",
    "Oman",
  ];

  const handleFilterChange = (e) => {
    const { name, value } = e.target;
    setSelectedFilters((prevFilters) => ({
      ...prevFilters,
      [name]: value,
    }));
    onFilterChange({ ...selectedFilters, [name]: value });
  };

  return (
    <div className="filter">
      <h2>Filters</h2>

      <div className="filter-item">
        <label htmlFor="topic">Topic:</label>
        <select name="topic" onChange={handleFilterChange}>
          <option value="">Select Topic</option>
          {uniqueTopic.sort().map((topic) => (
            <option key={topic} value={topic}>
              {topic}
            </option>
          ))}
        </select>
      </div>

      <div className="filter-item">
        <label htmlFor="endYear">End Year:</label>
        <select name="endYear" onChange={handleFilterChange}>
          <option value="">Select End Year</option>
          {endYear.sort().map((year) => (
            <option key={year} value={year}>
              {year}
            </option>
          ))}
        </select>
      </div>

      <div className="filter-item">
        <label htmlFor="sector">Sector:</label>
        <select name="sector" onChange={handleFilterChange}>
          <option value="">Select Sector</option>
          {uniqueSector.sort().map((sector) => (
            <option key={sector} value={sector}>
              {sector}
            </option>
          ))}
        </select>
      </div>

      <div className="filter-item">
        <label htmlFor="region">Region:</label>
        <select name="region" onChange={handleFilterChange}>
          <option value="">Select Region</option>
          {uniqueRegion.sort().map((region) => (
            <option key={region} value={region}>
              {region}
            </option>
          ))}
        </select>
      </div>

      <div className="filter-item">
        <label htmlFor="pest">PEST:</label>
        <select name="pest" onChange={handleFilterChange}>
          <option value="">Select PEST</option>
          {uniquePEST.sort().map((pest) => (
            <option key={pest} value={pest}>
              {pest}
            </option>
          ))}
        </select>
      </div>

      <div className="filter-item">
        <label htmlFor="source">Source:</label>
        <select name="source" onChange={handleFilterChange}>
          <option value="">Select Source</option>
          {uniqueSource.sort().map((source) => (
            <option key={source} value={source}>
              {source}
            </option>
          ))}
        </select>
      </div>

      <div className="filter-item">
        <label htmlFor="country">Country:</label>
        <select name="country" onChange={handleFilterChange}>
          <option value="">Select Country</option>
          {uniqueCountry.sort().map((country) => (
            <option key={country} value={country}>
              {country}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
}

export default Filter;
